### ISSUE TITLE
Some SF Symbols cases will raise errors.

### ISSUE THREAD

**Issue by zhangqifan** [lukepistrol/SFSymbolsMacro#1]
**Description**: I imported this repository as an SPM to my project, and here's my code:

```swift
import SFSymbolsMacro

@SFSymbol
enum Symbols: String {
    case figureChildAndLockFill = "figure.child.and.lock.fill"     // This symbol encounters an error: "figure.child.and.lock.fill" is not a valid SF Symbol.
    ... // other valid cases
}
```

And I can confirm that the 'invalid symbol' is in SF Symbols beta 5 for sure. The snapshot below shows it:

![CleanShot 2023-09-20 at 18 03 28@2x](https://github.com/lukepistrol/SFSymbolsMacro/assets/15685571/4e70e948-6173-4f04-993b-eb32f0ad404e)

So, why can some symbol names satisfy the compiler while others cannot?

**Environment**:
Xcode Version 15.0 (15A240d)
SF Symbols Beta 5

**Comment by lukepistrol** [comment]
I guess you're running `macOS Ventura`?

If so, this is expected behavior, since the compiler runs on your macOS and it does not know about those new symbols as they are only available on Ventura.

**Comment by zhangqifan** [comment]
Yep, you're right. It's my fault. Thanks for the reply.
